name: CI Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest  # Sets up a virtual machine to run the job on (ubuntu-latest, windows-latest, macos-latest)
    
    services:
      mongo:
        image: mongo:5.0
        ports: ['27017:27017']
        options: >-
          --health-cmd="mongosh --eval 'db.adminCommand(\"ping\")'"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Wait for MongoDB port to be ready
      - name: Wait for MongoDB
        run: |
          sudo apt-get update
          sudo apt-get install -y netcat-openbsd
          until nc -z localhost 27017; do
            echo "Waiting for MongoDB..."
            sleep 2
          done

      # Setup the entertainment_api
      - name: Install entertainment_api dependencies
        working-directory: ./src
        run: npm install
      
      - name: Start the entertainment_api
        working-directory: ./src
        env: 
          MONGO_URI: mongodb://localhost:27017/entertainment
        run: |
          PORT=5000 node app.js > server.log 2>&1 &

      - name: Debug Entertainment Catalog API startup
        working-directory: ./src
        run: |
          sleep 5
          cat server.log

      - name: Show listening ports
        run: |
          sleep 5
          sudo lsof -i -P -n | grep LISTEN

      - name: Wait for Entertainment API
        working-directory: ./src
        run: |
          npx wait-on --timeout 60000 http://localhost:5000/entertainment/health

      - name: Run Entertainment postman API tests with Newman
        working-directory: .
        run: |
          npm install newman
          npx newman run postman/Entertainment_basis.postman_collection.json

# Run docker test
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install docker-compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.23.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Show current directory
        run: |
          pwd
          ls -la

      - name: Run Dockerized Tests
        run: |
          # Build and start all services, stop all containers when one exits
          docker-compose -f ./docker-compose.test.yml up --build --abort-on-container-exit
          
          # Tear down containers and volumes after tests
          docker-compose -f ./docker-compose.test.yml down --volumes